name: Pitara Stories
collections:
  shakuntala:
    output: true
  khirer-putul:
    output: true
  thakumar-jhuli-kalabati:
    output: true
  thakumar-jhuli-others:
    output: true
  tuntunir-boi:
    output: true
  desh-bidesher-golpo:
    output: true  
  betal-panchabingshati:
    output: true  
    
