name: Pitara Stories
collections:
  shakuntala:
    output: true
  khirer-putul:
    output: true
  thakumar-jhuli-kalabati:
    output: true
  thakumar-jhuli-others:
    output: true
  tuntunir-boi:
    output: true
  desh-bidesher-golpo:
    output: true  
  betal-panchabingshati:
    output: true  
  thakumar-jhuli-others:
    output: true  
  gaddalika-prabaha:
    output: true
url: "https://lucidette.github.io/pitara-jekyll" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap    
